name: SonarQube Analysis

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install SonarQube Scanner
        run: npm install -g sonarqube-scanner

      - name: SonarQube Analysis
        run: |
          sonar-scanner \
            -X \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=sqa_c252c3aea72574b6e6bca0436be27ba113970124


       

